/** Subway Builder Modding API v1.0.0 - Game State Types */

import type { Coordinate, BuildType, DisplayType, TrackType, RouteShape } from './core';

// =============================================================================
// STATION DATA STRUCTURES
// =============================================================================

export interface NearbyStation {
  stationId: string;
  walkingTime: number;
}

export interface Station {
  id: string;
  name: string;
  coords: Coordinate;
  trackIds: string[];
  trackGroupId: string;
  buildType: BuildType;
  stNodeIds: string[];
  routeIds: string[];
  createdAt: number;
  /**
   * Stations within walking distance, with the walk time in seconds. Used as
   * the basis for catchment/transfer calculations.
   */
  nearbyStations: NearbyStation[];
}

/**
 * A proximity-merged group of stations treated as a single interchange (the
 * same grouping shown on the in-game schematic). Returned by
 * `gameState.getStationGroups()`.
 * @added Re-derived from the shipped build.
 */
export interface StationGroup {
  id: string;
  /** IDs of the stations merged into this interchange group. */
  stationIds: string[];
}

// =============================================================================
// TRACK DATA STRUCTURES
// =============================================================================

export interface Track {
  id: string;
  coords: Coordinate[];
  buildType: BuildType;
  displayType: DisplayType;
  type: TrackType;
  reversable: boolean;
  interactable: boolean;
  length: number;
  startElevation: number;
  endElevation: number;
  trackType: string;
  waterIntersectionPercentage: number;
  createdAt: number;
}

// =============================================================================
// TRAIN DATA STRUCTURES
// =============================================================================

export interface TrainMotion {
  speed: number;
  acceleration: number;
}

export interface TrackProgress {
  trackId: string;
  headProgress: number;
  tailProgress: number;
  triggeredSignalIds: string[];
}

export interface TrainWindow {
  tracks: TrackProgress[];
  headStComboProgress: number;
  tailStComboProgress: number;
  coords: Coordinate[];
  signalIds?: string[];
}

export interface CurrentStComboInfo {
  index: number;
  gapFromHeadToEndOfRoute: number;
  timeAtStop: number | null;
  timeAtStopEnd: number | null;
  endStNodeId: string;
}

export interface Train {
  id: string;
  routeId: string;
  length?: number;
  cars?: number;
  trainType?: string;
  currentStComboInfo?: CurrentStComboInfo;
  motion?: TrainMotion;
  windows?: {
    train: TrainWindow;
    warning: TrainWindow;
  };
}

// =============================================================================
// ROUTE DATA STRUCTURES
// =============================================================================

export interface StNode {
  id: string;
  center: Coordinate;
  trackIds: string[];
  buildType: BuildType;
}

export interface SignalReference {
  signalId: string;
  areaCovered: 'all' | string;
}

export interface PathSegment {
  trackId: string;
  reversed: boolean;
  length: number;
  signals: SignalReference[];
}

export interface StCombo {
  startStNodeId: string;
  endStNodeId: string;
  path: PathSegment[];
  distance: number;
}

export interface StComboTiming {
  stNodeId: string;
  stNodeIndex: number;
  arrivalTime: number;
  departureTime: number;
}

export interface TrainSchedule {
  highDemand: number;
  mediumDemand: number;
  lowDemand: number;
}

export interface Route {
  id: string;
  name?: string;
  bullet?: string;
  color?: string;
  textColor?: string;
  shape?: RouteShape;
  carsPerTrain?: number;
  idealTrainCount?: number;
  trainType?: string;
  trainSchedule?: TrainSchedule;
  tempParentId?: string | null;
  stations?: Station[];
  stNodes?: StNode[];
  stCombos?: StCombo[];
  stComboTimings?: StComboTiming[];
}

// =============================================================================
// DEMAND & POPULATION TYPES
// =============================================================================

/**
 * A location with jobs and residents. The aggregate `jobs`/`residents` are the
 * induced-demand levers, but actual ridership is generated by the {@link Pop}
 * commuter groups referenced in `popIds` (a pop must exist for a person to
 * travel — bumping `residents`/`jobs` alone only changes the displayed totals).
 *
 * Matches `DemandPointSchema` in the build: `id`, `location` (`[lon, lat]`),
 * `jobs` (int ≥ 0), `residents` (int ≥ 0), `popIds`. The `*ModeShare` fields
 * are computed by the simulation at runtime and are not part of the saved
 * schema — treat them as read-only.
 */
export interface DemandPoint {
  id: string;
  /** `[longitude, latitude]`. */
  location: Coordinate;
  jobs: number;
  residents: number;
  /** IDs of the commuter groups ({@link Pop}) anchored to this point. */
  popIds: string[];
  /** Computed at runtime (mode split of residents). Read-only. */
  residentModeShare: ModeChoiceStats;
  /** Computed at runtime (mode split of workers). Read-only. */
  workerModeShare: ModeChoiceStats;
}

/**
 * A commuter group traveling between a residence demand point (`residenceId`)
 * and a job demand point (`jobId`). `size` people make this trip; the commute
 * simulation assigns them to nearby stations by catchment and records the
 * outcome in `lastCommute`. Scaling `size` (or adding pops) is what actually
 * moves ridership.
 *
 * Saved schema (`PopSchema`) covers `id`, `size`, `residenceId`, `jobId`,
 * `drivingSeconds`, `drivingDistance`, `drivingPath?`. The remaining fields are
 * populated by the simulation at runtime.
 */
export interface Pop {
  id: string;
  size: number;
  /** ID of the demand point where this group lives. */
  residenceId: string;
  /** ID of the demand point where this group works. */
  jobId: string;
  drivingSeconds: number;
  drivingDistance: number;
  drivingPath?: Coordinate[];
  homeDepartureTime: number;
  workDepartureTime: number;
  lastCommute: CompletedPopCommute;
}

/**
 * Live demand state held by the main store and consumed by the commute
 * simulation each cycle. `gameState.getDemandData()` returns this exact object;
 * mutating the Maps in place is the supported write path (no setter is exposed).
 *
 * Note the runtime shape keys the pops collection as `popsMap`, whereas the
 * on-disk `demand_data.json` / `DemandDataSchema` uses `pops` as a record — see
 * {@link DemandDataFile} in `schemas.d.ts`.
 */
export interface DemandData {
  points: Map<string, DemandPoint>;
  popsMap: Map<string, Pop>;
}

// =============================================================================
// METRICS & STATS TYPES
// =============================================================================

export interface RidershipStats {
  totalRidersPerHour: number;
  totalRiders: number;
  timeWindowHours: number;
}

export interface LineMetric {
  name: string;
  ridersPerHour: number;
  routeId?: string;
  routeBullet?: string;
  routeColor?: string;
  trainCount?: number;
  trainsPerHour?: number;
  revenuePerHour?: number;
}

export interface ModeChoiceStats {
  walking: number;
  driving: number;
  transit: number;
  unknown: number;
}

export interface CompletedCommute {
  popId: string;
  size: number;
  journeyEnd: number;
  journeyStart: number;
  origin: 'work' | 'home';
  stationRoutes: StationRoute[];
}

export interface CompletedPopCommute {
  modeChoice: ModeChoiceStats;
  transitPaths: TransitPath[];
  walking: WalkingCommute;
}

export interface WalkingCommute {
  time: number;
  distance: number;
}

export interface StationRoute {
  stationIds: string[];
  routeId: string;
}

export interface StationRidership {
  total: number;
  transfers?: number;
  byRoute?: Array<{ routeId: string; popCount: number }>;
}

export interface RouteRidership {
  byStation: Array<{ stationId: string; popCount: number }>;
}

export interface TransitPath {
  arrivalTime: number;
  departureTime: number;
  fromStopCoords: Coordinate;
  fromStopId: string;
  isDriving: boolean;
  isWalking: boolean;
  routeId: string;
  toStopCoords: Coordinate;
  toStopId: string;
}
